
language: python
python:
  - "3.8"
sudo: required

before_script:
  - pip install -r requirements.txt
script: python server.py


branches:
  only:
  - master

deploy:
  provider: heroku
  app: api-simplon
  api_key: $HEROKU_AUTH_TOKEN
  skip_cleanup: True
