
language: python
python:
  - "3.8"
sudo: required

services:
  - docker

before_script:
  - pip install -r requirements.txt
script: python server.py


branches:
  only:
  - master

deploy:
  provider: heroku
  app: api-simplon
  api_key:
    - secure: 
