
language: python
python:
  - "3.8"
sudo: required

before_script:
  - pip install -r requirements.txt
script: 
  - echo 'python' 

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: api-simplon
  skip_cleanup: True
